"""Criacao banco plantas

Revision ID: ba3c2a921ace
Revises: c1c75b58e286
Create Date: 2025-07-30 02:11:59.339272
"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'ba3c2a921ace'
down_revision = 'c1c75b58e286'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('grupos',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('nome', sa.String(length=100), nullable=False),
    sa.Column('codigo_convite', sa.String(length=255), nullable=False),
    sa.Column('data_cadastro', sa.DateTime(), server_default=sa.text('now()'), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('codigo_convite')
    )
    op.create_index(op.f('ix_grupos_id'), 'grupos', ['id'], unique=False)
    op.create_table('tipos_acao',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('nome', sa.String(length=50), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('nome')
    )
    op.create_index(op.f('ix_tipos_acao_id'), 'tipos_acao', ['id'], unique=False)
    op.create_table('tipos_cronograma',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('nome', sa.String(length=50), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('nome')
    )
    op.create_index(op.f('ix_tipos_cronograma_id'), 'tipos_cronograma', ['id'], unique=False)
    op.create_table('tipos_fertilizante',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('nome', sa.String(length=50), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('nome')
    )
    op.create_index(op.f('ix_tipos_fertilizante_id'), 'tipos_fertilizante', ['id'], unique=False)
    op.create_table('tipos_luminosidade',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('nome', sa.String(length=50), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('nome')
    )
    op.create_index(op.f('ix_tipos_luminosidade_id'), 'tipos_luminosidade', ['id'], unique=False)
    op.create_table('tipos_rega',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('nome', sa.String(length=50), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('nome')
    )
    op.create_index(op.f('ix_tipos_rega_id'), 'tipos_rega', ['id'], unique=False)
    op.create_table('tipos_role',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('nome', sa.String(length=50), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('nome')
    )
    op.create_index(op.f('ix_tipos_role_id'), 'tipos_role', ['id'], unique=False)
    op.create_table('tipos_vento',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('nome', sa.String(length=50), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('nome')
    )
    op.create_index(op.f('ix_tipos_vento_id'), 'tipos_vento', ['id'], unique=False)
    op.create_table('grupos_users',
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('grupo_id', sa.Integer(), nullable=False),
    sa.Column('role_id', sa.Integer(), nullable=False),
    sa.Column('data_cadastro', sa.DateTime(), server_default=sa.text('now()'), nullable=True),
    sa.ForeignKeyConstraint(['grupo_id'], ['grupos.id'], ),
    sa.ForeignKeyConstraint(['role_id'], ['tipos_role.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('user_id', 'grupo_id')
    )
    op.create_table('plantas',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('grupo_id', sa.Integer(), nullable=False),
    sa.Column('nome', sa.String(length=100), nullable=False),
    sa.Column('descricao', sa.Text(), nullable=True),
    sa.Column('foto_url', sa.String(length=255), nullable=True),
    sa.Column('tipo_rega_id', sa.Integer(), nullable=False),
    sa.Column('quantidade_ml_rega', sa.Integer(), nullable=True),
    sa.Column('quantidade_dias_rega', sa.Integer(), nullable=False),
    sa.Column('quantidade_dias_fertilizante', sa.Integer(), nullable=True),
    sa.Column('tipo_fertilizante_id', sa.Integer(), nullable=True),
    sa.Column('tipo_luminosidade_id', sa.Integer(), nullable=False),
    sa.Column('tipo_vento_id', sa.Integer(), nullable=False),
    sa.Column('tipo_cronograma_id', sa.Integer(), nullable=False),
    sa.Column('data_cadastro', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.Column('data_atualizacao', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['grupo_id'], ['grupos.id'], ),
    sa.ForeignKeyConstraint(['tipo_cronograma_id'], ['tipos_cronograma.id'], ),
    sa.ForeignKeyConstraint(['tipo_fertilizante_id'], ['tipos_fertilizante.id'], ),
    sa.ForeignKeyConstraint(['tipo_luminosidade_id'], ['tipos_luminosidade.id'], ),
    sa.ForeignKeyConstraint(['tipo_rega_id'], ['tipos_rega.id'], ),
    sa.ForeignKeyConstraint(['tipo_vento_id'], ['tipos_vento.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_plantas_id'), 'plantas', ['id'], unique=False)
    op.create_table('logs_atividade',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('planta_id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('tipo_acao_id', sa.Integer(), nullable=True),
    sa.Column('data_atividade', sa.DateTime(), server_default=sa.text('now()'), nullable=True),
    sa.ForeignKeyConstraint(['planta_id'], ['plantas.id'], ),
    sa.ForeignKeyConstraint(['tipo_acao_id'], ['tipos_acao.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_logs_atividade_id'), 'logs_atividade', ['id'], unique=False)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_logs_atividade_id'), table_name='logs_atividade')
    op.drop_table('logs_atividade')
    op.drop_index(op.f('ix_plantas_id'), table_name='plantas')
    op.drop_table('plantas')
    op.drop_table('grupos_users')
    op.drop_index(op.f('ix_tipos_vento_id'), table_name='tipos_vento')
    op.drop_table('tipos_vento')
    op.drop_index(op.f('ix_tipos_role_id'), table_name='tipos_role')
    op.drop_table('tipos_role')
    op.drop_index(op.f('ix_tipos_rega_id'), table_name='tipos_rega')
    op.drop_table('tipos_rega')
    op.drop_index(op.f('ix_tipos_luminosidade_id'), table_name='tipos_luminosidade')
    op.drop_table('tipos_luminosidade')
    op.drop_index(op.f('ix_tipos_fertilizante_id'), table_name='tipos_fertilizante')
    op.drop_table('tipos_fertilizante')
    op.drop_index(op.f('ix_tipos_cronograma_id'), table_name='tipos_cronograma')
    op.drop_table('tipos_cronograma')
    op.drop_index(op.f('ix_tipos_acao_id'), table_name='tipos_acao')
    op.drop_table('tipos_acao')
    op.drop_index(op.f('ix_grupos_id'), table_name='grupos')
    op.drop_table('grupos')
    # ### end Alembic commands ###